title: Hacerfak
author: 
  name: Eder Gross Cichelero
  email: hacerfak4@gmail.com
email: hacerfak4@gmail.com
description: >- # Descrição curta para o Google (Meta Description)
  Dicas avançadas de Linux e tutoriais de Debian| Um blog dedicado ao conhecimento.
url: "https://hacerfak.com.br" # Mude para seu URL do github quando publicar
baseurl: ""
permalink: /:year/:month/:day/:title/
lang: pt-BR
locale: pt_BR
  # Fuso horário
timezone: "America/Sao_Paulo"

# ID do Google Analytics (GA4)
google_analytics: G-1BK324EDDE

webmaster_verifications:
  google: 78fcJ6RU8T8KcwG0c7BJAZpjRY6duoWOjWG9p3n5Uzk
  bing: 44A86B1888654478DBDFD35ED2111049

# Paginação
paginate: 6
paginate_path: "/blog/:num/"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Variáveis Sociais
social:
  name: Eder Gross Cichelero
  github: https://github.com/Hacerfak
  youtube: https://www.youtube.com/channel/UCHUWL6eACdcEROIiLGff1vw
  spotify: https://open.spotify.com/artist/7rU9vqJmap4T5Qg0QoeXPo
  soundcloud: https://soundcloud.com/hacerfak-music
  steam: https://steamcommunity.com/id/hacerfak


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/